### ISSUE TITLE
Add custom problems

### ISSUE THREAD

**Issue by winf-hsos** [fredoverflow/karel#11]
Hi, is there a way to add a set of custom problems? I am using the software with my students, and for assessments and practice it would be great if this were possible. Preferably in an easy to work with format, such as JSON.

Thanks
Nicolas

**Comment by fredoverflow** [comment]
There have been multiple attemps at adding custom problems, but they all failed for a non-technical reason: coming up with good/interesting/instructive problems is actually much harder than it might seem at first glance.

The problems are stored in src/main/kotlin/logic/Problem.kt
`karelsFirstProgram` starts at line 44. The goal string at line 46 is taken from the machine view, activated via Ctrl+Shift+M.

Grüße nach Osnabrück

**Comment by winf-hsos** [comment]
Thanks for the reply. I'll see whether I find some interesting new problems and try to add them. I believe this is hard, haven't thought it all the way through yet. 

I find your version of Karel very useful in teaching the basics of algorithmic thinking. Thanks for creating and sharing it! I picked up on the idea of Karel, and I am currently developing a web-based environment with a similar goal. Although 95% of my students figured out eventually how to install Java on their computer and run a .jar file, there is a number who doesn't know how to get Karel running. Despite the excellent documentation you wrote here. I believe a web-based environment could ease this pain. 

Thanks again!

Grüße nach Hamburg
Nicolas
