### ISSUE TITLE
while

### ISSUE THREAD

**Issue by spiderrider** [fredoverflow/karel#7]
Hi,
if I take the procedure "void moveToWall()" I get the error message "while loops are not allowed yet". Why do you show it as an example?
Harald

**Comment by fredoverflow** [comment]
`while` loops are the central theme of 2.y.z problems. They are not needed for 1.y.z problems, hence they are forbidden by default. If you want to use `while` loops for 1.y.z problems anyway, just provide an empty solution for any of the 2.y.z problems:
```
void hangTheLampions()
{
    // while loops are allowed everywhere now
}
```
